baseURL = 'https://xederro.github.io/blog/'
languageCode = 'en-us'
title = 'Xederro - blog'
publishDir = 'docs/'
theme = 'PaperMod'
[params.assets]
disableFingerprinting = true
[[module.mounts]]
source = 'blog/files'
target = 'static/files'
[[module.mounts]]
source = 'static'
target = 'static'

[outputs]
home = ['html', 'rss']
section = ['html', 'rss']
taxonomy = ['html']
term = ['html']

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts"
weight = 10

[[menu.main]]
identifier = "Tags"
name = "Tags"
url = "/tags"
weight = 20

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
math = true
ShowFullTextinRSS = true
comments = true

[params.profileMode]
enabled = true
title = "Dawid Jabłoński"
subtitle = "Aspiring devops / back-end developer"
imageUrl = "https://avatars.githubusercontent.com/u/50398562?s=400&u=1aeee9736601dcefb084a2bb22118cb04b8ae3c3&v=4"
imageTitle = "Photo of me"
imageWidth = 120
imageHeight = 120

[[params.socialIcons]]
name = "github"
url = "https://github.com/xederro"

[[params.socialIcons]]
name = "kofi"
url = "https://ko-fi.com/xederro"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/dawidjablonski/"

[[params.socialIcons]]
name = "rss"
url = "./index.xml"

[services]
  [services.disqus]
    shortname = 'https-xederro-github-io-blog.disqus.com'