baseURL = 'https://xederro.github.io/blog/'
languageCode = 'en-us'
title = 'Xederro - blog'
publishDir = 'docs/'
theme = 'PaperMod'
[params.assets]
disableFingerprinting = true
[[module.mounts]]
source = 'blog/files'
target = 'static/files'

[[menu.main]]
identifier = "Archives"
name = "archives"
url = "https://xederro.github.io/blog/archives/"
weight = 30

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true

[params.profileMode]
enabled = true
title = "Dawid Jabłoński"
subtitle = "This is subtitle"

  [[params.profileMode.buttons]]
  name = "Archives"
  url = "/blog/archives"

  [[params.profileMode.buttons]]
  name = "Github"
  url = "https://github.com/xederro"

