baseURL = 'https://xederro.github.io/blog-hugo/'
languageCode = 'en-us'
title = 'Xederro - blog'
publishDir = 'docs/'
theme = 'PaperMod'
relativeURLs = true
[params.assets]
disableFingerprinting = true
[[module.mounts]]
source = 'files'
target = 'static/files'